version: '3'

services:
  db:
    container_name: photo_competition_database
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: photo_competition
    image: broder1ck/photo_competition
    command: bash -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input && python manage.py runserver"
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db


#  gateway:
#    container_name: foodgram_gateway
#    image: itsmeemichka/foodgram_gateway
#    env_file: .env
#    ports:
#      - 7000:80
#    volumes:
#      - static:/static
#      - media:/media
#    depends_on:
#      - backend

volumes:
  pg_data:
  static:
  media:
