# Generated by Django 5.0.1 on 2024-02-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_alter_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                default="bb1a79bf7a73cec584d3bc666019b707",
                max_length=255,
                verbose_name="Токен",
            ),
        ),
    ]
