name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.12.3'
    - name: Install dependencies
      uses: VaultVulp/action-pipenv@master
      with:
        command: install -d
    - name: Make envfile
      uses: SpicyPizza/create-envfile@master
      with:
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_DEBUG: ${{ secrets.DEBUG }}
        envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        envkey_SOCIAL_AUTH_VK_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_VK_OAUTH2_KEY }}
        envkey_SOCIAL_AUTH_VK_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_VK_OAUTH2_SECRET }}
        envkey_SCHEMA: ${{ secrets.SCHEMA }}
        envkey_DOMAIN: ${{ secrets.DOMAIN }}
        envkey_PHOTO_DELETE_TIME_SECONDS: ${{ secrets.PHOTO_DELETE_TIME_SECONDS }}
        file_name: .env
    - name: Setup database
      uses: ikalnytskyi/action-setup-postgres@v6 
      with:
        username: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASSWORD }}
        database: ${{ secrets.DB_NAME }}
        host: ${{ secrets.DB_HOST }}
        port: ${{ secrets.DB_PORT }}
    - name: Test
      uses: VaultVulp/action-pipenv@master
      with:
        command: run test
    - name: Pre-commit
      uses: VaultVulp/action-pipenv@master
      with:
        command: run pre-commit
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/photo_competition
            git pull
            pipenv install
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn.service
            sudo systemctl restart daphne.service
            sudo systemctl restart celery.service
            pipenv run python manage.py collectstatic --noinput
            pipenv run python manage.py migrate
