name: Django Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/photo_competition
            git pull
            pipenv install
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn.service
            sudo systemctl restart daphne.service
            sudo systemctl restart celery.service
            pipenv run python manage.py collectstatic --noinput
            pipenv run python manage.py migrate
