name: Test Workflow

on: push 

jobs:
 test:
   runs-on: ubuntu-latest
   
   services:
    image: postgres
    env:
    - POSTGRES_USER: postgres
    - POSTGRES_PASSWORD: postgres
    - POSTGRES_BD: postgres
    ports:
    - 5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
   
   steps:
   - uses: actions/checkout@master
   - name: Set up Python
   - uses: actions/setup-python@master
     with:
      python-version: 3.12

   - name: Install dependencies
   - uses: VaultVulp/action-pipenv@master
     with:
      command: install -d
   - name: Test
   - uses: VaultVulp/action-pipenv@master
     env:
        PG_HOST: postgres
        PG_USER: postgres
        PG_DATABASE: postgres
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports['5432'] }}
     with:
        command: run test
